version: '3.8'

services:
  your-service:
    image: testdb
    container_name: 'testdb-servuce'
    build:
      context: ./testdb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/socialMedia
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    external: true
