server:
  port: 8090

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**  # Simplified to match all under /users
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}
        - id: posts-service
          uri: http://localhost:8081
          predicates:
            - Path=/posts/**  # Simplified to match all under /posts
          filters:
            - RewritePath=/posts/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      expose: "*"
    endpoint:
      gateway:
        enabled: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty: DEBUG