server:
  port: 8090

spring:
  application:
    name: API-Gateway
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: actuator-route-users-service
          uri: http://socialmediaapp-users-service-1:8082
          predicates:
            - Path=/actuator/**
        - id: users-service
          uri: http://socialmediaapp-users-service-1:8082
          predicates:
            - Path=/users/**
        - id: posts-service
          uri: http://localhost:8081
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/posts/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  configprops:
    keys-to-sanitize: ""

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty: DEBUG