server:
  port: 8090


spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}
        - id: posts-service
          uri: http://localhost:8081
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/posts/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"
